// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWWKaXloag_S7T8Q8Tdmintt7r1uuNuE',
    appId: '1:219855743944:web:85d3bb99c6c7f655422efd',
    messagingSenderId: '219855743944',
    projectId: 'listapp-flutter',
    authDomain: 'listapp-flutter.firebaseapp.com',
    storageBucket: 'listapp-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEf6HwqN_JsGdhCdq5WqKN59SwhwabaoI',
    appId: '1:219855743944:android:b531e378d3170ae4422efd',
    messagingSenderId: '219855743944',
    projectId: 'listapp-flutter',
    storageBucket: 'listapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJZOrn16YIM8RztG9GZB6iPgq6lCIptd4',
    appId: '1:219855743944:ios:f82c6cadea4023b9422efd',
    messagingSenderId: '219855743944',
    projectId: 'listapp-flutter',
    storageBucket: 'listapp-flutter.appspot.com',
    iosBundleId: 'com.example.listapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJZOrn16YIM8RztG9GZB6iPgq6lCIptd4',
    appId: '1:219855743944:ios:2738cf50ac80cab0422efd',
    messagingSenderId: '219855743944',
    projectId: 'listapp-flutter',
    storageBucket: 'listapp-flutter.appspot.com',
    iosBundleId: 'com.example.listapp.RunnerTests',
  );
}
